### ISSUE TITLE
Web Meta Language in MPS

### ISSUE THREAD

**Issue by Clashsoft** [Clashsoft/Projects#14]
- [x] Konzepte ausarbeiten, die für ein Meta-Web-Framework notwendig sind (z.B. Komponenten, Services, ...) #9 
- [ ] Konzepte in MPS definieren
- [ ] Sonstige Sprachelemente von HTML in MPS definieren
- [ ] Parser und Generator Targets für Angular und React implementieren
